### PR TITLE
Adding AKS sock shop demo

### PR DESCRIPTION
**Pull request by kenazk**
Here's a successful run of the Workflow on the Demo account:

https://nebula.puppet.com/workflows/aks/runs/51/graph

### CODE REVIEW

**Comment by woodburndesigns** [comment]
@kenazk two things, I think it would be good to remove the manual gate here. I'd like to instead build an example to illustrate the value of that. Also, in chatting with @kyleterry the outputs supports an object with keys of `from` and `name`. I think that would be helpful to add to better illustrate whats happening.

**Comment by kenazk** [comment]
Made the manual gate change. 

I'm not sure what you mean by the second thing?

**Comment by woodburndesigns** [comment]
The second point is an optional improvement to add clarity to the outputs. We can skip for now I'll look into revisiting later.

**Comment by kenazk** [comment]
OK sounds good 👍

**Pull request merged**
